Repository SpongePowered/SpongeAPI, pull requests merged in 2019-02, with the labels that each got.

#1534 Add some helper methods for working with ServerBossBars
  src/main/java/org/spongepowered/api/entity/living/complex/EnderDragon.java
  src/main/java/org/spongepowered/api/entity/living/monster/Wither.java
Labels: status: needs review, version: 1.12, version: 1.13

#1934 add primary interaction Slot to ClickInventoryEvent
  src/main/java/org/spongepowered/api/event/item/inventory/ClickInventoryEvent.java
  src/main/java/org/spongepowered/api/event/item/inventory/CraftItemEvent.java
Labels: status: needs review, system: event, system: inventory, version: 1.12

#1930 Fix flowpowered links - site is down
  gradle/sponge.gradle
Labels: status: needs review, status: needs testing

#1960 Do not append spaces after CommandElements whose usages are empty.
  src/main/java/org/spongepowered/api/command/args/GenericArguments.java
Labels: status: ready to merge

#1915 Inventory Transfer Events
  src/main/java/org/spongepowered/api/event/item/inventory/ChangeInventoryEvent.java
  src/main/java/org/spongepowered/api/event/item/inventory/TransferInventoryEvent.java
Labels: branch: bleeding, status: input wanted, status: wip, system: event, system: inventory

#1677 updated javadoc for Event.getCause
  src/main/java/org/spongepowered/api/event/Event.java
Labels: status: ready to merge, type: javadoc

#1967 Delegate getNearbyEntities to getEntities
  src/main/java/org/spongepowered/api/world/extent/EntityUniverse.java
Labels: status: needs review, status: needs testing

#1969 Add EventContextKeys.USED_HAND
  src/main/java/org/spongepowered/api/event/cause/EventContextKeys.java
Labels: status: needs review, status: needs testing, type: feature request
